.github/workflows/tox.yml
test/gce/scenarios/linux/requirements.yml
test/vagrant/scenarios/molecule/default-compat/destroy.yml

1. Fix typo
2. Install collection from galaxy, it's a simply way to install collection
3. Use ansible installed by tox and remove `apt-get install ansible`
Related to https://github.com/ansible-community/molecule-plugins/pull/111#discussion_r1139980578

Optimize CI

---

README.md

With newly added plugins, the list has to be updated.
Signed-off-by: Arnaud Patard <apatard@hupstream.com>

README.md: Update plugin list

---

src/molecule_plugins/vagrant/playbooks/prepare.yml

This PR:
- install python3 only when `ansible_system == Linux`
- closes #109

install python3 only when ansible_system == Linux

---

src/molecule_plugins/vagrant/modules/vagrant.py

Since molecule https://github.com/ansible-community/molecule/pull/3887, the jinja is now autoescaping, which leads to things like:
virtualbox.customize [&#39;modifyvm&#39;, :id, &#39;--natdnshostresolver1&#39;, &#39;on&#39;]
in the Vagrantfile.
Add some "safe" filters to solve this.

Add safe filter for raw args (vagrant)

---

.ansible-lint
.ansible-lint-ignore
.pre-commit-config.yaml
requirements.yml
tools/extract_plugin_names.py
tools/generate-templates.sh
tools/toml_to_json.py
tox.ini

Enhancement: Generate cookie cutter templates and apply linting on them

---

src/molecule_plugins/azure/cookiecutter/{{cookiecutter.molecule_directory}}/{{cookiecutter.scenario_name}}/create.yml

`Standard_A0` Is gonna get deprecated on august 2024. 
`Standard_B1ms` is the same price (15$), has a burst capability ( good for ansible testing workload ), has 2GB of ram
the `Standard_B1s` has 1GB RAM and half the price but from my experience 1GB is bothersome when installing large packages with yum, maintainer input is appreciated
`Centos 8_5-gen2` looks stable, couldn't find any known bugs or problems with a google search, newer base package make life easier.

deprecated(azure): replace VM type

---

src/molecule_plugins/docker/playbooks/create.yml

This change allows specifying a different docker runtime. 
The use case is to use sysbox runtime whenever the playbooks use the systemd.

feat: Add runtime entry on docker create playbook

---

src/molecule_plugins/vagrant/modules/vagrant.py

To avoid changes in molecule.util breaking the vagrant module, let's get rid of the dependency by:
- embedded the recursive dict merge function
- replace template handling by our own code. (and keep the autoescaping enabled)
Moreover, it will make it easier to use community.vagrant since molecule is not needed anymore.

src/molecule_plugins/vagrant/modules/vagrant.py: Get rid of molecule dependency

---

MANIFEST.in

When packaging as .deb/.rpm with setuptools (sometime without setuptools_scm), some required template files are excluded from the final packaging result, unless specify them within `MANIFEST.in`.
See https://setuptools.pypa.io/en/latest/userguide/miscellaneous.html
See https://packaging.python.org/en/latest/guides/using-manifest-in

enhancement: Including files in source distributions with MANIFEST.in

---

doc/ec2/platforms.rst
src/molecule_plugins/ec2/cookiecutter/{{cookiecutter.molecule_directory}}/{{cookiecutter.scenario_name}}/create.yml

This is a small change, but I think it would be useful for people to be able to set an instance profile if the EC2 instance needs access to other AWS resources, like S3 buckets.

Allow for setting EC2 instance profile

---

src/molecule_plugins/podman/playbooks/create.yml
src/molecule_plugins/podman/playbooks/destroy.yml
tox.ini

fixes #73 
This PR tries to avoid the hardcoding of `ansible_async_dir` introduced in [molecule-podman PR #139](https://github.com/ansible-community/molecule-podman/pull/139) by using `ansible.builtin.getent` to get the `$USER` passwd data and by using `ansible.builtin.config` to get `async_dir` from the shell configuration. `ansible_async_dir` will be set only if the two home paths are different and the value will pick up the changes set from the rest of the controller set-up.
`tox.ini` is also updated to allow `lookup('env', 'USER')` to work in the CI.

podman: change ansible_async_dir only when $HOME is redefined

---

.ansible-lint-ignore
src/molecule_plugins/ec2/cookiecutter/{{cookiecutter.molecule_directory}}/{{cookiecutter.scenario_name}}/destroy.yml

This PR seeks to fix the issue described in https://github.com/ansible-community/molecule-plugins/issues/136 and https://github.com/ansible-community/molecule-plugins/issues/121.
Currently, when using the EC2 Molecule plugin, issuing a `molecule test` command will cause _all_ other EC2 instances in the subnet to be deleted. This is because the "destroy" phase gets run before the "create" phase, plus the fact that when the `amazon.aws.ec2_instance` Ansible module is called with no `instance_id` attribute (as is the case or a fresh `molecule test` command), the operation applies to all EC2 instance.
I've added in a block that checks that the `instance_config` is _not empty_ before attempting to destroy EC2 instance.

Prevent empty destroy from deleting other EC2 instances

---

src/molecule_plugins/ec2/cookiecutter/{{cookiecutter.molecule_directory}}/{{cookiecutter.scenario_name}}/destroy.yml

The upstream code there can call  their get_default_vpc(), which will fail if our users do not have one in their AWS account.
It is common practice to remove it and build a more restricted one - causing errors for users that do so.
ref #46

pass vpc_subnet_id explicitly to avoid amazon.aws error

---

src/molecule_plugins/docker/playbooks/create.yml

Else the build will attempt to use a network that hasn't been created yet. This is essentially a resurrection of ehartmann's PR against molecule-docker before its death.
Closes: #24

docker/create.yml: create network before building local image

---

src/molecule_plugins/podman/playbooks/create.yml
src/molecule_plugins/podman/playbooks/destroy.yml
tox.ini

fixes #181 
https://github.com/ansible-community/molecule-plugins/commit/b5509a19465ba39cfedff0e6450524620a2d6d2f uses `$USER` to get the home for the current user, but if the controller does not run `login(1)`, like in containers, the variable is not set. This PR uses `whoami` to get the current user.
**EDIT** Since the `ansible_async_dir` setting logic is not needed anymore (see https://github.com/ansible-community/molecule-plugins/pull/182#issuecomment-1807426732) this PR now removes it in `create.yml` and `destroy.yml`.

podman: remove ansible_async_dir setting logic

---

.gitignore
tools/generate-templates.sh

This fix avoids the following error on OSX when executing tox lint `sed: -i or -i may not be used with stdin`

Fix lint execution on osx and ignore generate roles files

---

conftest.py
test/azure/functional/conftest.py
test/azure/functional/test_azure.py
test/containers/functional/conftest.py
test/containers/functional/test_containers.py
test/docker/conftest.py
test/docker/test_func.py
test/ec2/functional/conftest.py
test/ec2/functional/test_ec2.py
test/gce/functional/conftest.py
test/gce/functional/test_func.py
test/gce/test_driver.py
test/podman/test_func.py
test/vagrant/functional/conftest.py
test/vagrant/functional/test_func.py

With the move of the molecule tests outside the src it is necessary to vendor the dep fixtures here.
Related: https://github.com/ansible/molecule/pull/4070

Remove dependency to molecule.test

---

src/molecule_plugins/docker/driver.py
src/molecule_plugins/docker/playbooks/create.yml

Add support to configuring docker shm_size in molecule platform configuration. This is already available in the docker_container_module. I believe this solves #215.

Support the shm_size docker configuration option

---

src/molecule_plugins/docker/driver.py

docker intercepts errors from requests and returns its own errors, so we actually need to expect a docker error here

Handle Docker errors correctly

---

src/molecule_plugins/docker/playbooks/create.yml

Customize loop label on all tasks to avoid to print registry password on log.

Don't print registry password in loop label

---

src/molecule_plugins/docker/driver.py
src/molecule_plugins/docker/playbooks/create.yml

Support plumbing `cache_from` parameter in `create.yml` playbook.
This parameter is very useful for external CI/CD caches, especially where there is no persistence between runs as described in https://docs.docker.com/build/cache/backends/
Molecule works great in my environment, but spends a long time rebuilding images in `community.docker.docker_image`:
```
===============================================================================
Build an Ansible compatible image (new) -------------------------------- 87.64s
```
I'd like to pass `cache_from` rather than fork the `create.yml` playbook, to make molecule tests faster for CI/CD servers and our developers: we do this already for adhoc `docker-compose` + `ansible` based tests. Thank you!

docker: support cache_from in create playbook

---

src/molecule_plugins/ec2/cookiecutter/{{cookiecutter.molecule_directory}}/{{cookiecutter.scenario_name}}/create.yml

The driver code expects an pkcs1 key for fetching the windows password. Make sure we generate the correct key type.
Current code fails with:
```
Traceback (most recent call last):
File "/usr/local/bin/molecule", line 8, in <module>
sys.exit(main())
^^^^^^
File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1130, in __call__
return self.main(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1055, in main
rv = self.invoke(ctx)
^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1657, in invoke
return _process_result(sub_ctx.command.invoke(sub_ctx))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1404, in invoke
return …
```

Enforce pkcs1 for ec2 keys

---

src/molecule_plugins/azure/driver.py
src/molecule_plugins/ec2/driver.py
src/molecule_plugins/gce/driver.py
src/molecule_plugins/vagrant/driver.py

This file assumes Jinja templating for the port parameter and passes a Jinja-style "{{ port }}".
https://github.com/ansible/molecule/blob/main/src/molecule/command/login.py#L105
When it reaches molecule, it is subsituted in  this file and is done by python calling `.format()` on the string. That causes it to not render correctly and gives users issues running molecule login.
ref: https://github.com/ansible-community/molecule-plugins/issues/239

fix #239 , use python-style templating instead of Jinja in the plugins login_cmd_template

---

src/molecule_plugins/podman/driver.py
src/molecule_plugins/podman/playbooks/create.yml

* when the podman driver runs the `create` playbook, we'll add a
`owner=molecule` label to the containers we create
* in `reset`, we'll delete containers (eventually everything?) that has
the label `owner=molecule`

implement reset for podman driver

---

src/molecule_plugins/docker/driver.py

* if the user hasn't installed the `[docker]` extra, they won't have
`docker` to `import`, so don't make `import docker` required in the
docker driver's `reset`.
* fixes #166
an alternative implementation could be
```py
for driver in drivers():
with suppress(ImportError):
driver.reset()
```
in this section: https://github.com/ansible/molecule/blob/4e2592e5d77b181133243b8b685933f6daff3897/src/molecule/command/reset.py#L49
pros of this PR's implementation:
* scoped to just docker driver
pros of `with suppress(ImportError)` in `molecule`:
* driver authors don't have to remember to `try/except ImportError: pass` in their `reset()`

docker: allow `import docker` in `reset` to fail

---

test/vagrant-plugin/scenarios/molecule/box_url/molecule.yml

Replacing obsolete box/checksum with `CentOS-8-Vagrant-8.4.2105-20210603.0.x86_64.vagrant-libvirt.box` / `37cc017738bf12cafce3a97c4de73526452da6332cc5c0516723988644e62620`.
With these values in `test/vagrant-plugin/scenarios/molecule/box_url/molecule.yml` the test passes.

Vagrant: `test_vagrant_root[box_url]` fails due to missing box (#274)

---

src/molecule_plugins/gce/playbooks/tasks/create_linux_instance.yml
src/molecule_plugins/gce/playbooks/tasks/create_windows_instance.yml

GCE: Added network tags support
Tags are used to identify valid sources or targets for network firewalls. 
For example: It allows to get ssh access to run Molecule tests
In molecule.yml
platforms:
- name: 'molecule-instance'
tags:
items:
- 'allow-ssh'

GCE: Added network tags support

---

src/molecule_plugins/gce/playbooks/tasks/create_linux_instance.yml

Adding retry to the task waiting for ssh to make it more robust

feat: add retry for gce plugin when waiting for SSH

---

src/molecule_plugins/vagrant/modules/vagrant.py

Vagrant recently added a box_architecture flag, which defaults to the current platform, which breaks my need to test amd64 images on a M2/3/4-based MacOS device.  This patch adds the glue needed to pass the required architecture down to the lower-level VagrantFile
For reference:
https://github.com/hashicorp/vagrant/commit/51adb125477b50e5acce6e6ad39e38d7b3cd7b3b

add box_architecture config to parameters

---

src/molecule_plugins/podman/playbooks/create.yml

This was the case in the past (and is still the case for the Docker
driver), but was accidentally changed in an unrelated refactoring.
Fixes: e9d56496261807a5174c1347123b49e629c2490b

podman: default the hostname to the name of the platform

---

requirements.yml
src/molecule_plugins/docker/driver.py

Includes fixes related to https://github.com/psf/requests/issues/6707 and https://github.com/docker/docker-py/issues/3256
Fixes #256.

Update the `community.docker` collection

---

README.md

Update the README to explain the release process.

Add docs on creating new releases

---

src/molecule_plugins/vagrant/modules/vagrant.py

Reopen of #277, reproducing here for convenience. 
Per the discussion there, the merge conflicts have been resolved, and the linting error seems to be gone.
---
The current implementation in `src/molecule_plugins/vagrant/modules/vagrant.py` generates a Vagrantfile with excessive white space (a total of 42 empty lines with the `molecule.yml` sample in `driver.py`), and some indentation issues for the `overwrite` entries, making troubleshooting less pleasant. The proposed changes greatly reduce blank lines and keep the Vagrantfile in a more easily readable form.
I have first attempted to clear white space by `{%-` / `-%}`, however this proved challenging with indentation and other desired whitespace (separating blocks of code in the Vagrantfile). Eventually I went with adding …

Vagrant: Reducing whitespace in Vagrantfile

---

src/molecule_plugins/gce/playbooks/tasks/create_linux_instance.yml
src/molecule_plugins/gce/playbooks/tasks/create_windows_instance.yml

Missing the until key for the wait_for module in the gce plugin. Apparently, it doesn't work when the `until` is missing.

bug: missing until for retry in gce plugin

---

doc/openstack/platforms.rst
src/molecule_plugins/openstack/driver.py
src/molecule_plugins/openstack/playbooks/create.yml

Adds options to the OpenStack plugin to set a list of floating IP pools from which to choose a floating IP or to turn off the allocation of a public IP.
Supersedes https://github.com/ansible-community/molecule-plugins/pull/229 and https://github.com/ansible-community/molecule-plugins/pull/243

Openstack add public IP options

---

src/molecule_plugins/ec2/driver.py

Using the `molecule login` command with the Molecule EC2 plugin and a Windows target (winrm connection method) fails with the error:
```
[16:20:02:648] [83832:f0258240] [ERROR][com.winpr.commandline] - [log_error]: Failed at index 4 [/cert-tofu]: Unexpected keyword
```
The docs for FreeRDP state that the `cert-tofu` CLI option has been deprecated and changed to `cert:tofu`. This option skips the certificate validation step, which may sense for this use case. See https://manpages.debian.org/unstable/freerdp2-x11/xfreerdp.1.en.html.
I tested my fix locally, and changing `/cert-tofu` to `/cert:tofu` fixed the issue. I am running molecule on an M4 macbook with FreeRDP version 3.10.2.

Fix deprecated xfreerdp option for winrm targets of EC2 plugin

---

.github/workflows/release.yml
.github/workflows/tox.yml
conftest.py
pyproject.toml
src/molecule_plugins/docker/driver.py
src/molecule_plugins/podman/driver.py
src/molecule_plugins/vagrant/modules/vagrant.py
test/azure/functional/test_azure.py
test/containers/functional/test_containers.py
test/docker/test_func.py
test/ec2/functional/test_ec2.py
test/gce/functional/test_func.py
test/openstack/test_func.py
test/podman/test_func.py
test/vagrant-plugin/functional/test_func.py

From https://github.com/ansible/molecule/pull/4359 `util.run_command` should now replaced with `app.run_command`.
Fixes https://github.com/ansible/molecule/issues/4372

[Molecule v25.1.0] Replace util.run_command with app.run_command

---

src/molecule_plugins/ec2/cookiecutter/{{cookiecutter.molecule_directory}}/{{cookiecutter.scenario_name}}/destroy.yml

This PR changes the logic of deleting resources of the EC2 driver. Without that change security groups and keypairs will stay because the tasks will be skipped.
The tasks `Write Molecule instance configs` changes the when condition of the block immediately. This will skip the following tasks regardless of their when conditions. Moving the tasks `Write Molecule instance configs` to the end of the block will execute the cleanup of Security groups and keypairs according to their own when condition.

EC2: Change logic of deleting resources

---

.github/workflows/release.yml

When #294, I didn't notice that the python version was not inside quotes, leading to python version being parsed as 3.1 and not 3.10. Breaking the release workflow.
Add missing quotes.

.github/workflows/release.yml: Fix release
